name: best_verifier
description: "A comprehensive private directory for identity and asset verification."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Finalized dependencies for the project
  external_app_launcher: ^4.0.3
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # ADD THIS LINE TO FIX EXIT CODE 255
  flutter_launcher_icons: ^0.13.1

# This section is also required by the icon generator tool
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png" # Make sure an image exists here or point to a valid one

flutter:
  uses-material-design: true
